### ISSUE TITLE
Rename to gprime-common

### ISSUE THREAD

**Issue by vzvikaramba** [Galaxy-MSM8916/android_device_samsung_gprimelte-common#4]

**Comment by vzvikaramba** [comment]
Yeah, this isn't happening.

**Comment by minz1** [comment]
@vince2678 Why isn't this happening?

**Comment by gerrit-galaxy-msm8916** [comment]
@minz1 I don't have a fortuna device (any of the older gprimes), and @Has_007, @ZIM555 and @GuaiYiHu have been inactive. It's all up to them since they have the older gprime devices.
